### ISSUE TITLE
Support matplotlib > 3.3.2

### ISSUE THREAD

**Issue by alexlenail** [deeptools/pyGenomeTracks#356]
https://github.com/deeptools/pyGenomeTracks/blob/488a6d3f9e81c6ca1af9f90484445070ed9c7024/requirements.txt#L2

pyGenomeTracks does not support recent versions of matplotlib. I believe the first error message you might run into is: 

```
AttributeError: 'YAxis' object has no attribute '_gridOnMajor'
```
for which there is some helpful information here: https://github.com/plotly/plotly.py/issues/2913

**Comment by lldelisle** [comment]
Hi,
We restrict matplotlib versions because we got bad experiences in the past. So we decided not to support matplotlib versions we did not tested. It appears that PGT is working well with 3.3.3, I don't have any error message. I am testing the other ones and will write a PR so the next PGT versions will support later versions of matplotlib.

**Comment by lldelisle** [comment]
I wrote a PR #358

**Comment by lldelisle** [comment]
Solved in version 3.7
